### ISSUE TITLE
cannot load trained model using Ranger

### ISSUE THREAD

**Issue by ElisonSherton** [lessw2020/Ranger-Deep-Learning-Optimizer#26]
Hi There!

Thanks for putting together this code for Rectified Adam with Lookahead optimizer. I used this optimization function to train my model with fastai and successfully trained the model.

I exported the model using 
```python
feature = 'silhouette'
learn.export(f'{feature}_efficientnet-b3.pkl')
```

and later during inference I am trying to load the learner using
```python
from ranger import Ranger
feature = 'silhouette'
learn = load_learner(path = model_path, file = f'{feature}_efficientnet-b3.pkl')
```
I have defined the model path properly in the previous cells. But for some reason, I cannot load the learner. The file cannot locate the module `ranger.ranger`. Can someone please help me fix this issue?

Here's a screenshot of the error for your reference.
![Screenshot from 2020-04-02 15-18-02](https://user-images.githubusercontent.com/45599762/78234922-7cedf300-74f5-11ea-8273-e29ad9dcc5cb.png)

Thanks & Regards,
Vinayak.

**Comment by lessw2020** [comment]
Hi @ElisonSherton  - is this fastai 1.1 or 2.0?
I've used ranger + efficientnet on both and had no issues so it definitely can be done.
In 2.0 ranger is built into fastai directly now but you can also use the import version.
Anyway if you can clarify what version and also post the full notebook if possible?  
I suspect the issue is how it's being embedded with the export but also need to see how you pulled in efficientnet and from what repo (i.e. rwightman vs lukemelas).
