### ISSUE TITLE
Gradient centralization was updated

### ISSUE THREAD

**Issue by hadaev8** [lessw2020/Ranger-Deep-Learning-Optimizer#32]
https://github.com/Yonghongwei/Gradient-Centralization/commit/d46e4c54ae47b730d0805694849f106c41828e97

**Comment by lessw2020** [comment]
Thanks @hadaev8  - the changes have been added into ranger2020.py thanks in part to Yonghongwei posting an updated ranger on his site.  
I've tested on private dataset and perf looks really good!
Will integrate into the main ranger.py shortly.  Please test out ranger2020.py if you have time and let me know if any issues otherwise closing this for now.
Thanks!

**Comment by hadaev8** [comment]
I belive all len(list(grad.size())) should be replaced with grad.dim()

**Comment by lessw2020** [comment]
I think you are correct. Let me update and test 
 Thanks for your help pointing this.

**Comment by hadaev8** [comment]
Why you have new variable name here?
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer/blob/master/ranger/ranger2020.py#L185
