### ISSUE TITLE
Not able to save the model_state_dict.

### ISSUE THREAD

**Issue by shikha10799** [lessw2020/Ranger-Deep-Learning-Optimizer#36]
Hi I was trying to save the model checkpoints after each epoch using the below code.But only the state dictionary of the zeroth epoch got stored and none of the others.Does the ranger optimiser object support state_dict ? If yes then how can I save it after each epoch?

`out_model = os.path.join(args.model_dir, 'model.th')
    with open(out_model, 'wb') as f:
        torch.save(model.state_dict(), f)
    print("Model is dumped")`

**Comment by lessw2020** [comment]
Hi @shikha10799  - Ranger won't impact your ability to save your state_dict.
Looking at the code above, I think you just need to simplify it to the path rather than passing in a file handle:
torch.save(model.state_dict(),path) is all that is needed. 
 PyTorch will do the file opening etc and I suspect your issue is the file handle may not be closed in your code (ideally you should use a with context manager) and thus it can't re-save on the second and later attempt.
I'll go ahead and close this for now but let me know if any other questions.
