### ISSUE TITLE
Dose  any one  has  tested  this  composed   Optimizer?

### ISSUE THREAD

**Issue by heartInsert** [lessw2020/Ranger-Deep-Learning-Optimizer#4]

**Comment by pabloppp** [comment]
You have some benchmarks agains Adam and another variations of RAdam in here https://github.com/mgrankin/over9000

**Comment by heartInsert** [comment]
Yes ,  because  I  test  Ranger   in  my  dataset,  it   seems  not  better  than  normal   Adam .
Thansk  for  your    reply  ,I will   check  this  repo    https://github.com/mgrankin/over9000

**Comment by lessw2020** [comment]
Hi heartInsert - we have tested with both Ranger and RangerLars (aka Over9000).  Ranger currently outperforms, but you will have to test with some additional learning rates, and currently recommend using a flat lr for about .70% of training and then cosine anneal from there.  
Also, highly recommend trying out Mish instead of ReLU along with the above.  We just beat the FastAI 5 epoch leaderboards using the above - I'll have an article on Medium about it out shortly.  
Hope that helps!

**Comment by heartInsert** [comment]
Thanks   for  your   recommendation , friend ,   I  will  definitely  try  more  lr_scheduler  later  , 
 but   what      impressive    me   most  is  that  , everyone   seems   talk    about   Mish   in   today's  morning ,  it  is   gonna  be   a  paper  to  read.

Waiting   for  your  article.

**Comment by heartInsert** [comment]
Yes,  your   recommendation :  `[Adam,RAdam,Ranger]  with   a flat lr for about .70% of training and then cosine anneal from there.  `   shows  a  better  capability   in  convergence.
 I  tested  them  all  and   get  the  best   convergence   ability   with    ` Ranger   with    cosine annealing`  in  training  stage.

**Comment by lessw2020** [comment]
Great, glad to hear it. 
We'll have an update on the code here shortly as rwightman has redone a new implementation of the lookahead portion to fix the load/save issues, and fgfm has added a new sync option (customizable) for how to update weights at the end of each epoch.

**Comment by lessw2020** [comment]
Well disregard  we don't have a save/load issue in the current code after all,  thanks to keeping everything in one integrated codebase.
I'll add the variable sync option likely next week but may not be as useful as I was thinking.
Anyway, I'll close this issue since the flat + cosine anneal seems to have addressed your issue here.
Thanks!
